# -*- coding: utf-8 -*-
"""Model Building of Web Phishing .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j486zwouwY6Hx4hddyrPTxP2wmFpTRdI

## **Download the Dataset**
"""

from google.colab import drive

import pandas as pd

path = "/content/drive/MyDrive/dataset_website.csv"
ds = pd.read_csv(path)

ds.head()

#Splitting the data as independent and dependent

#Removing index column in independent dataset

x=ds.iloc[:,1:31].values
y=ds.iloc[:,-1].values
print(x,y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

"""# **Model Building**
## Start building Machine Learning Model

There are several Machine Learning algorithms to be used depending on the data you are going to process such as images, sound, text, and numerical values. The algorithms can be chosen according to the objective. As the dataset which we are using is a Classification dataset  we can use the following algorithms,

* Logistic Regression
* Random Forest Regression / Classification
* Decision Tree Regression / Classification
* K-Nearest Neighbors
* Support Vector Machine

In order to get appropriate predictions, the dataset can be trained with any of the above algorithms.

# **1. Choose The Appropriate Model**
## Working with **Logistic Regression Model**
"""

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)

"""# **2. Calculate the Accuracy of the** **Model**"""

y_pred1=lr.predict(x_test)
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,y_pred1)
log_reg

"""# **3. Save the Model**"""

import pickle
pickle.dump(lr,open('Phishing_website.pkl','wb'))